DB:
  image: mysql
  environment:
    - MYSQL_DATABASE=moodle
    - MYSQL_ROOT_PASSWORD=moodle
    - MYSQL_USER=moodle
    - MYSQL_PASSWORD=moodle
moodle:
   image: matheusveleci/docker-moodle:latest
   links:
    - DB
   ports:
    - "8080:80"
   environment:
    - MOODLE_URL=http://127.0.0.1:8080
